<?php

namespace WpContent\Cli\Builder;

use WpContent\Cli\ResourceType;

class Generator
{
    use EnsurePathTrait;

    private readonly string $root;

    public function __construct(?string $rootDir = null)
    {
        $this->root = $rootDir ?? (string) getcwd();
    }

    /**
     * Scaffold the main file of a new plugin/theme inside a directory named
     * after its slug. Returns the created directory, or null on failure.
     *
     * @param array<string, string> $headers
     */
    public function generateMainFile(ResourceType $type, string $slug, array $headers): ?string
    {
        [$prefix, $filename] = match ($type) {
            ResourceType::Plugin => ["<?php\n /**\n", "$slug.php"],
            ResourceType::Theme => ["/**\n", 'style.css'],
        };

        $contents = $prefix . $this->renderHeaders($headers);

        $workdir = $this->ensurePath($this->root . '/' . $slug, true);
        if (!is_string($workdir)) {
            return null;
        }

        if (!@file_put_contents($workdir . '/' . $filename, $contents)) {
            return null;
        }

        return $workdir;
    }

    /**
     * @param array<string, string> $headers
     */
    private function renderHeaders(array $headers): string
    {
        $contents = '';
        foreach ($headers as $header => $value) {
            $contents .= " * $header: $value\n";
        }

        return $contents . " *\n * Generated by WPC-CLI Generator (https://wp-content.io). \n */\n\n";
    }
}
